{
 "title": "EventMesh with Camel",
 "description": "EventMesh Monitoring Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pod:container_memory_usage_bytes:sum {namespace=\"demo\"}"
    }
   ]
  },
  {
   "title": "Camel Processing Time (Max)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_camel_exchange_processing_max_seconds"
    }
   ]
  },
  {
   "title": "Camel Max Processing time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_camel_route_processing_max_seconds"
    }
   ]
  },
  {
   "title": "Inflight count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_camel_context_exchanges_inflight_count"
    }
   ]
  },
  {
   "title": "Current Camel Running",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_camel_route_running_count"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{namespace=\"demo\"}"
    }
   ]
  },
  {
   "title": "Total Completed Camel Route",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_camel_context_exchanges_completed_total"
    }
   ]
  }
 ]
}